### ISSUE TITLE
Retrieve projects belonging to other users

### ISSUE THREAD

**Issue by alexandermendes** [PyBossa/enki#17]
Hi,

We have multiple project owners but want to use the same program to help analyse results using enki. Now that the PyBossa API returns data related to the authenticated user first, we would have to specify the api key for every project. Can we just add an option to pass the "all=1" argument to the pbclient, on initialisation?

**Comment by alexandermendes** [comment]
One option: https://github.com/PyBossa/enki/pull/18

**Comment by teleyinex** [comment]
Yes, this is mandatory. @therealmarv is working on some of those details and your solution for enki is really simple and nice :-) @therealmarv can you take a look?

**Comment by alexandermendes** [comment]
Thanks, although I just realised that this wasn't working as the queries for loading tasks/task runs also needed the "all=1" argument. How about just always searching all objects, for simplicity? Have updated the PR! (https://github.com/PyBossa/enki/pull/18/commits/53fa9c9955132824c392ade77938feeff6bc9f3f)

**Comment by alexandermendes** [comment]
Just wanted to check if there's any chance of getting a fix for this soon? Thanks!

**Comment by therealmarv** [comment]
sorry, this bug get out of sight for me. I will do some more PyBossa bugfixing this week. Thanks for pinging me.

**Comment by teleyinex** [comment]
Solved! Sorry for the long delay. I'll upload the new version to pypi after closing this issue.

**Comment by alexandermendes** [comment]
Cool, thanks 😃
